#include "XYZWriter.h"
#include <iomanip>
#include <stdexcept>

XYZWriter::XYZWriter(const std::string& filename)
    : numParticles(0), headerWritten(false) {
    file.open(filename, std::ios::out);
    if (!file.is_open()) {
        throw std::runtime_error("Failed to open XYZ file: " + filename);
    }
}

XYZWriter::~XYZWriter() {
    if (file.is_open()) {
        file.close();
    }
}

void XYZWriter::writeHeader(size_t numParticles) {
    if (!headerWritten) {
        this->numParticles = numParticles;
        headerWritten = true;
    }
}

void XYZWriter::writeFrame(const System& system) {
    if (!headerWritten) {
        writeHeader(system.getNumParticles());
    }

    file << numParticles << "\n";
    file << "Generated by Simulation\n";

    for (size_t i = 0; i < numParticles; ++i) {
        const std::shared_ptr<const Particle> particle = system.getParticle(i);
        // const auto& particle = system.getParticle(i);
        const double& x_position = particle->get_x_position();
        const double& y_position = particle->get_y_position();
        const double& z_position = particle->get_z_position();
        file << "P " << std::fixed << std::setprecision(6) 
             << x_position << " " << y_position << " " << z_position << "\n";
    }
}

void XYZWriter::close() {
    if (file.is_open()) {
        file.close();
    }
}
